// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const _APIKEY_ANDROID = String.fromEnvironment('APIKEY_ANDROID');
  static const _APIKEY_WEB = String.fromEnvironment('APIKEY_WEB');
  static const _APIKEY_WIN = String.fromEnvironment('APIKEY_WIN');
  static const _APIKEY_IOS = String.fromEnvironment('APIKEY_IOS');
  static const _APIKEY_MAC = String.fromEnvironment('APIKEY_MAC');

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _APIKEY_WEB,
    appId: '1:966074492991:web:820e4c8c1676877782f08a',
    messagingSenderId: '966074492991',
    projectId: 'civiconnect-13aeb',
    authDomain: 'civiconnect-13aeb.firebaseapp.com',
    storageBucket: 'civiconnect-13aeb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _APIKEY_ANDROID,
    appId: '1:966074492991:android:fa8089007b0cdefe82f08a',
    messagingSenderId: '966074492991',
    projectId: 'civiconnect-13aeb',
    storageBucket: 'civiconnect-13aeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _APIKEY_IOS,
    appId: '1:966074492991:ios:650fb586f21a535382f08a',
    messagingSenderId: '966074492991',
    projectId: 'civiconnect-13aeb',
    storageBucket: 'civiconnect-13aeb.firebasestorage.app',
    iosBundleId: 'com.example.civiconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _APIKEY_MAC,
    appId: '1:966074492991:ios:650fb586f21a535382f08a',
    messagingSenderId: '966074492991',
    projectId: 'civiconnect-13aeb',
    storageBucket: 'civiconnect-13aeb.firebasestorage.app',
    iosBundleId: 'com.example.civiconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _APIKEY_WIN,
    appId: '1:966074492991:web:6abb24f369951ab482f08a',
    messagingSenderId: '966074492991',
    projectId: 'civiconnect-13aeb',
    authDomain: 'civiconnect-13aeb.firebaseapp.com',
    storageBucket: 'civiconnect-13aeb.firebasestorage.app',
  );

}