// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgcJ3fneU3c1o5-yvm10JM9llib7Deahs',
    appId: '1:966074492991:web:820e4c8c1676877782f08a',
    messagingSenderId: '966074492991',
    projectId: 'civiconnect-13aeb',
    authDomain: 'civiconnect-13aeb.firebaseapp.com',
    storageBucket: 'civiconnect-13aeb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc4Kb5kYGc1gL6QORfcMhah2aYls4w9rk',
    appId: '1:966074492991:android:fa8089007b0cdefe82f08a',
    messagingSenderId: '966074492991',
    projectId: 'civiconnect-13aeb',
    storageBucket: 'civiconnect-13aeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdeKwG_QDUuM_xln_VYGh8IWkv_o-Cy6I',
    appId: '1:966074492991:ios:650fb586f21a535382f08a',
    messagingSenderId: '966074492991',
    projectId: 'civiconnect-13aeb',
    storageBucket: 'civiconnect-13aeb.firebasestorage.app',
    iosBundleId: 'com.example.civiconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdeKwG_QDUuM_xln_VYGh8IWkv_o-Cy6I',
    appId: '1:966074492991:ios:650fb586f21a535382f08a',
    messagingSenderId: '966074492991',
    projectId: 'civiconnect-13aeb',
    storageBucket: 'civiconnect-13aeb.firebasestorage.app',
    iosBundleId: 'com.example.civiconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgcJ3fneU3c1o5-yvm10JM9llib7Deahs',
    appId: '1:966074492991:web:6abb24f369951ab482f08a',
    messagingSenderId: '966074492991',
    projectId: 'civiconnect-13aeb',
    authDomain: 'civiconnect-13aeb.firebaseapp.com',
    storageBucket: 'civiconnect-13aeb.firebasestorage.app',
  );
}
