include: package:lints/recommended.yaml

linter:
  rules:
    # Style
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    avoid_print: true
    prefer_single_quotes: true

    # Naming Conventions
    camel_case_types: true

    # Documentation
    slash_for_doc_comments: true

    # Best Practices
    annotate_overrides: true
    avoid_types_on_closure_parameters: true
    public_member_api_docs: true

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false