name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Test e Checkstyle
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Test connection
      run: curl "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json"

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      working-directory: src  # Specifica la cartella src
      run: flutter pub get

    - name: Run Checkstyle (Linter)
      working-directory: src
      run: flutter analyze

    - name: Run tests
      working-directory: src
      run: flutter test

    - name: Build APK
      working-directory: src
      run: flutter build apk --release

    - name: Build iOS
      if: runner.os == 'macOS'
      working-directory: src
      run: flutter build ios --release --no-codesign
