name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Test e Checkstyle
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Puoi scegliere 'zulu' o 'adopt' se preferisci
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24'
        channel: 'stable'

    - name: Install dependencies
      working-directory: src  # Specifica la cartella src
      run: flutter pub get

    - name: Run Checkstyle (Linter)
      working-directory: src
      run: flutter analyze

    - name: Run tests
      working-directory: src
      run: flutter test

    - name: Build APK
      working-directory: src
      run: flutter build apk --release
